[project]
name = "fix-struct-asym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gemmi>=0.7.0",
    "tqdm>=4.0.0",
]
